# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: joatmon08/tech-portfolio
    steps:
    - name: fix image
    - run: |
      # Pull the Node.js Docker image:
      docker pull node:22-alpine
      # Create a Node.js container and start a Shell session:
      docker run -it --rm --entrypoint sh node:22-alpine
      # Verify the Node.js version:
      node -v # Should print "v22.17.0".
      # Verify npm version:
      npm -v # Should print "10.9.2".
    - uses: actions/checkout@v2
    - name: Install dependencies and static website
      run: |
        cd website
        yarn install
        yarn build
    - name: Push to Github Pages branch
      run: |
        cd website/build/tech-portfolio
        touch .nojekyll
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} INPUT_DIRECTORY=$(pwd) publish.sh
        
